/**
 * Inline the orbit + calque CSS into a TypeScript module that the
 * OrbitUI wrapper can `import` and inject inside its shadow root.
 * Runs before `tsc` so the generated module compiles into dist.
 *
 * Output: src/orbit-ui-styles.ts (gitignored — regenerated on every
 * build). The bundled `dist/faust-orbit-ui.css` is still produced
 * separately by the `cat …` step in package.json's build, for the
 * legacy `FaustOrbitUI` consumers that link the stylesheet directly.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');

const css =
  readFileSync(resolve(root, 'src/faust-orbit-ui.css'), 'utf-8') +
  '\n' +
  readFileSync(resolve(root, 'src/orbit-calque.css'), 'utf-8');

// Escape backticks and ${} so the CSS can sit inside a TS template
// literal without being interpreted.
const escaped = css.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

const out =
  '// AUTO-GENERATED — do not edit. Regenerated by scripts/build-styles.mjs.\n' +
  '// Concatenation of src/faust-orbit-ui.css and src/orbit-calque.css,\n' +
  '// inlined so the OrbitUI wrapper can inject it inside its shadow root\n' +
  '// without depending on the host loading a stylesheet link.\n' +
  '\n' +
  'export const ORBIT_UI_STYLES: string = `' + escaped + '`;\n';

writeFileSync(resolve(root, 'src/orbit-ui-styles.ts'), out);
console.log('[build-styles] wrote src/orbit-ui-styles.ts (' + css.length + ' chars of CSS)');
